#debug or release
RUN_MODE_DEV : debug
RUN_MODE : release
env: dev
app:
    PAGE_SIZE : 10
    JWT_SECRET : 23347$040412
server:
    HTTP_PORT : 6001
    READ_TIMEOUT : 60
    WRITE_TIMEOUT : 60
database:
    TYPE : mysql
    USER : 
    PASSWORD : 
    #127.0.0.1:3306
    HOST : 
    NAME : 
    TABLE_PREFIX : 
log:
    LOG_TYPE : gray
    LOG_UDP : udp://g02.graylog.xxx.com:5504
    LOG_FIELDS : item:goddd
    LOG_LEVEL : -1
    IS_SHOW_CONSOLE : true
consul:
    CONSUL_URL : consul.xxx.com
    CONSUL_LIST_NAME : xxx/config_center/
api:

http_fix:
    dev : dev.
    test : t-
    prepare : pre-
    production : 
