#debug or release
RUN_MODE11 : debug

app:
    PAGE_SIZE : 10
    JWT_SECRET : 23347$040412
server:
    HTTP_PORT : 6001
    READ_TIMEOUT : 60
    WRITE_TIMEOUT : 60
database:
    TYPE : 
    USER : 
    PASSWORD : 
    #127.0.0.1:3306
    HOST : 
    NAME : 
    TABLE_PREFIX : 
log:
    LOG_TYPE : gray
    LOG_UDP : udp://g02.graylog.xxxx.com:5504
    LOG_FIELDS : item:ginlog
    LOG_LEVEL : -1
    IS_SHOW_CONSOLE : true
consul:
    CONSUL_URL : test.consul.xxxx.com
    CONSUL_LIST_NAME : gaodun/config_center/
api:
